# Lab01_Pytorch_Tensors - Introduction to PyTorch and Tensor

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
%cd '/content/drive/MyDrive/CV_course2021/Pytorch_ML/Lec1'

/content/drive/MyDrive/CV_course2021/Pytorch_ML/Lec1


In [ ]:
import torch

Tensors in Pytorch

In [ ]:
# In Pytorch it's not array anymore, so dim is used to describe about it's shape!
x_dim0 = torch.tensor(2)
x_dim1 = torch.tensor([1, 2, 3])
x_dim2 = torch.tensor([[1,2,3]])
x_dim3 = torch.tensor([[[1,2,3]]])
print(x_dim0.dim()) # ~ x.ndim in numpy
print(x_dim1.dim())
print(x_dim2.dim())
print(x_dim3.dim())

0
1
2
3


In [ ]:
# In spite of the reason above, It's still likely to NumPy in use!
# But we should call it tensor instead of array!
A = torch.randint(0,255, (2,2)) # ~ np.random.randint(0, 255, (2, 2))
print(type(A))
print(A)
print(A.shape) # can also use view!
print(A.dim())

<class 'torch.Tensor'>
tensor([[ 76, 198],
        [170, 195]])
torch.Size([2, 2])
2


Operator and Linear Algebra extension

In [11]:
A = torch.tensor([[1,2],[3,4]])
B = torch.tensor([[2,3],[4,5]])

# Basic
AaddB = A+B
print('>>> A + B =\n', AaddB)
AminB = A-B
print('>>> A - B =\n', AminB)
Amul2 = A*2
print('>>> A * 2 =\n', Amul2)
AmulB = A*B
print('>>> Hamadard Product: A * B =\n', AmulB)
AdivB = A/B
print('>>> Elements wise: A / B =\n', AdivB)
Apow2 = A**2
print('>>> A**2 =\n', Apow2)
_2powA = 2**A
print('>>> 2**A =\n', _2powA)
Asin = torch.sin(A) # affect a function!
print('>>> sin(A) =\n', Asin)

# Linear Algebra
AB = torch.mm(A,B)# AB = torch.dot(A,B) and A.dot(B) - 1D arrays only!!! To anoying!
print('>>> AB =\n',AB)
Ainv = torch.linalg.pinv(A.type(torch.float32)) # Too anoying!!!!!
print('>>> A^-1 =\n', Ainv)
print('>>> A.T =\n', A.T)
Adet = torch.linalg.det(A.type(torch.float32))
print('>>> detA =\n', Adet)
print('>>> traceA =\n', A.trace())
Afro_norm = torch.linalg.norm(A.type(torch.float32), ord = 'fro')
print('>>> A forbenious norm =\n', Afro_norm)

# ...

>>> A + B =
 tensor([[3, 5],
        [7, 9]])
>>> A - B =
 tensor([[-1, -1],
        [-1, -1]])
>>> A * 2 =
 tensor([[2, 4],
        [6, 8]])
>>> Hamadard Product: A * B =
 tensor([[ 2,  6],
        [12, 20]])
>>> Elements wise: A / B =
 tensor([[0.5000, 0.6667],
        [0.7500, 0.8000]])
>>> A**2 =
 tensor([[ 1,  4],
        [ 9, 16]])
>>> 2**A =
 tensor([[ 2,  4],
        [ 8, 16]])
>>> sin(A) =
 tensor([[ 0.8415,  0.9093],
        [ 0.1411, -0.7568]])
>>> AB =
 tensor([[10, 13],
        [22, 29]])
>>> A^-1 =
 tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])
>>> A.T =
 tensor([[1, 3],
        [2, 4]])
>>> detA =
 tensor(-2.0000)
>>> traceA =
 tensor(5)
>>> A forbenious norm =
 tensor(5.4772)


In [ ]:
# So with linear algebra, it's so anoying! Because before some opertors we have to change the type of tensor!


Types

In [ ]:
x = torch.tensor([1,2,4,5])
y = torch.tensor([1.4, 1.6])
print(x.type())
print(y.type())

torch.LongTensor
torch.FloatTensor


In [ ]:
x_float = x.type(torch.float) # ~ x.float
y_int = y.type(torch.long) # x.long
print(x_float.type())
print(y_int.type())

torch.FloatTensor
torch.LongTensor


Other functions

In [12]:
A = torch.tensor([[1, 3], [4, 5]]).float()
B = torch.tensor([[4,5]])
identity = torch.eye(A.shape[0]) # only eye
zeros = torch.zeros_like(A)
ones = torch.ones_like(A)
range_10 = torch.arange(10)
permutation_10 = torch.randperm(10)
linspace = torch.linspace(0, 10, 10000)
concatenate = torch.cat((A,B), dim = 0)
meanA_0 = torch.mean(A, dim = 0, keepdim = True)
maxA_1 = torch.max(A, dim = 1, keepdim = True)
argmaxA = torch.argmax(A, dim = 1, keepdim = True)
# ...
print('>>> identity\n', identity)
print('>>> zeros\n', zeros)
print('>>> ones\n',ones)
print('>>> range 10: {}, dtype = {}'.format(range_10,range_10.type()))
print('>>> permutation 10:', permutation_10)
print('>>> linspace\n', linspace)
print('>>> concatenate axis = 0\n', concatenate)
print('>>> mean A axis = 0\n', meanA_0)
print('>>> max A axis = 1\n', maxA_1)
print('>>> argmax A ax')

>>> identity
 tensor([[1., 0.],
        [0., 1.]])
>>> zeros
 tensor([[0., 0.],
        [0., 0.]])
>>> ones
 tensor([[1., 1.],
        [1., 1.]])
>>> range 10: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), dtype = torch.LongTensor
>>> permutation 10: tensor([5, 4, 7, 6, 9, 8, 0, 2, 1, 3])
>>> linspace
 tensor([0.0000e+00, 1.0001e-03, 2.0002e-03,  ..., 9.9980e+00, 9.9990e+00,
        1.0000e+01])
>>> concatenate axis = 0
 tensor([[1., 3.],
        [4., 5.],
        [4., 5.]])
>>> mean A axis = 0
 tensor([[2.5000, 4.0000]])
>>> max A axis = 1
 torch.return_types.max(
values=tensor([[3.],
        [5.]]),
indices=tensor([[1],
        [1]]))
>>> argmax A ax


Iteam selection and manipulation

In [13]:
A = torch.arange(30).reshape(5,6)
print(A)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29]])


In [14]:
print(A[:,1]) # column 1

tensor([ 1,  7, 13, 19, 25])


In [15]:
print(A[1,:]) # row 1

tensor([ 6,  7,  8,  9, 10, 11])


In [16]:
print(A[:2,:3]) # first 2 rows, 3 columns

tensor([[0, 1, 2],
        [6, 7, 8]])


In [23]:
x = torch.arange(3)
y = [5,4,1]
print(A[x,y])

tensor([ 5, 10, 13])


Torch Tensor to Numpy Array

In [26]:
A = torch.arange(10)
B = A.numpy()
print(B)
print(type(B))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


Exercise: Softmax_stable

In [29]:
def Softmax_stable(Z):
  return torch.exp(Z-torch.max(Z, dim =1, keepdim = True)[0])/torch.sum(torch.exp(Z-torch.max(Z, dim =1, keepdim = True)[0]), dim = 1, keepdim = True)

In [30]:
Z = torch.tensor([[1,2,1,3,5,1],
                  [4,5,2,1,2,4],
                  [1,3,6,7,3,7]])
A = Softmax_stable(Z)
print(A)

tensor([[0.0148, 0.0401, 0.0148, 0.1091, 0.8064, 0.0148],
        [0.1985, 0.5395, 0.0269, 0.0099, 0.0269, 0.1985],
        [0.0010, 0.0076, 0.1528, 0.4155, 0.0076, 0.4155]])


In [31]:
print(torch.sum(A, dim = 1, keepdim = True))

tensor([[1.0000],
        [1.0000],
        [1.0000]])
